spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
